name: micros
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.1
  xml2json: ^6.2.7
  http: ^1.5.0
  flutter_bloc: ^9.1.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_svg: ^2.2.1
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.11.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/icons/



flutter_gen:
  output: lib/common/gen
  integrations:
    flutter_svg: true
